name:                vhdl-testbench-gen
version:             0.1.0.0
github:              "bhrollins/vhdl-testbench-gen"
license:             BSD3
author:              "Brendan Rollins"
maintainer:          "brendan.h.rollins@gmail.com"
copyright:           "2022 Brendan Rollins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bhrollins/vhdl-testbench-gen#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- filepath
- parsec
- directory

library:
  source-dirs: src

executables:
  vhdl-testbench-gen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vhdl-testbench-gen

tests:
  vhdl-testbench-gen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vhdl-testbench-gen
